-- MySQL Script generated by MySQL Workbench
-- dom 24 feb 2019 17:24:05 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema auth
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `auth` ;

-- -----------------------------------------------------
-- Schema auth
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `auth` DEFAULT CHARACTER SET utf8 ;
USE `auth` ;

-- -----------------------------------------------------
-- Table `auth`.`actions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auth`.`actions` ;

CREATE TABLE IF NOT EXISTS `auth`.`actions` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `refer_action` VARCHAR(150) NOT NULL COMMENT 'Refer action like a url',
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `auth`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auth`.`roles` ;

CREATE TABLE IF NOT EXISTS `auth`.`roles` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `description` VARCHAR(500) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `enabled` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '0 (visible), 1 (invisible) ',
  `created` DATETIME NOT NULL,
  `updated` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `auth`.`roles_has_actions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auth`.`roles_has_actions` ;

CREATE TABLE IF NOT EXISTS `auth`.`roles_has_actions` (
  `roles_id` INT(10) UNSIGNED NOT NULL,
  `actions_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`roles_id`, `actions_id`),
  INDEX `fk_roles_has_actions_actions1_idx` (`actions_id` ASC),
  INDEX `fk_roles_has_actions_roles1_idx` (`roles_id` ASC),
  CONSTRAINT `fk_roles_has_actions_actions1`
    FOREIGN KEY (`actions_id`)
    REFERENCES `auth`.`actions` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roles_has_actions_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `auth`.`roles` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `auth`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auth`.`users` ;

CREATE TABLE IF NOT EXISTS `auth`.`users` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `password` VARCHAR(256) CHARACTER SET 'utf8' NOT NULL,
  `first_name` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `last_name` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `phone_number` VARCHAR(20) NOT NULL,
  `date_of_birth` DATE NOT NULL,
  `google_auth_ref` VARCHAR(50) NULL,
  `enabled` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'visible (0), invisible(1)',
  `created` DATETIME NOT NULL DEFAULT now(),
  `updated` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `auth`.`users_has_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auth`.`users_has_roles` ;

CREATE TABLE IF NOT EXISTS `auth`.`users_has_roles` (
  `users_id` INT(10) UNSIGNED NOT NULL,
  `roles_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`users_id`, `roles_id`),
  INDEX `fk_users_has_roles_roles1_idx` (`roles_id` ASC),
  INDEX `fk_users_has_roles_users_idx` (`users_id` ASC),
  CONSTRAINT `users_has_roles_ibfk_1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `auth`.`roles` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `users_has_roles_ibfk_2`
    FOREIGN KEY (`users_id`)
    REFERENCES `auth`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `auth`.`session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auth`.`session` ;

CREATE TABLE IF NOT EXISTS `auth`.`session` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(100) NOT NULL,
  `last_login` DATETIME NOT NULL,
  `expired` DATETIME NOT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
